### ISSUE TITLE
question on the function tucker_reg

### ISSUE THREAD

**Issue by smszmr** [Hua-Zhou/TensorReg#2]
Hi Prof. Zhou,

I have a question on the function tucker_reg. This function returns the parameters \beta in "glmstat2", which has a 1 \times 5 cell. I think the last one should be the final estimation. But there are only 2 numbers in the last item, and I'm not sure how to use them for new prediction on y.

Another question comes when I try to use the Sparse Tucker regression. There are always error massages, which are showed in the attached picture. I think there may be some modifications in the toolbox which are not updated online, is that right?
<img width="699" alt="sparse" src="https://user-images.githubusercontent.com/22016945/27806743-5ee57cdc-600a-11e7-87c4-25c4f1860004.png">

Many thanks!

**Comment by Hua-Zhou** [comment]
> This function returns the parameters \beta in "glmstat2", which has a 1 \times 5 cell. I think the last one should be the final estimation. But there are only 2 numbers in the last item, and I'm not sure how to use them for new prediction on y.

I don't quite understand your question. The first output of the `tucker_reg` function is the estimated regression coefficients for the regular (non-tensor) covariates. The second output is the tensor regression coefficient represented as a tucker tensor.  Type `help tucker_reg` in Matlab command line to see the documentation for the `tucker_reg` function. 

> Another question comes when I try to use the Sparse Tucker regression. There are always error massages, which are showed in the attached picture. I think there may be some modifications in the toolbox which are not updated online, is that right?

Do you mean sparse Kruskal (CP) regression or sparse Tucker regression? You say Sparse Tucker regression but the error message shows function `kruskal_sparsereg`. Also can you give a minimal example that reproduces the error message. That could save tremendous amount of time.

**Comment by smszmr** [comment]
Hi Prof. Zhou,

Thanks for your reply.

For the first problem, I just to want to make sure that I get the estimated coefficients correctly. And your answer helped me on it.

For the second question, in fact, the problem happened both in sparse Kruskal (CP) regression and sparse Tucker regression. And actually, when I run the codes in your tutorial "Kruskal (CP) regression", in the "Sparse Kruskal logistic regression, 2D covariates" section, the error massage always show up. That's why I think there may be some modifications in the toolbox which are not updated online.

Many thanks!

**Comment by Hua-Zhou** [comment]
I just ran the `demo_kruskal.m` file on my computer and didn't see any errors. My system is Mac OS 10.12.5 and Matlab 2017a. One thing you can try is to uninstall TensorReg toolbox and re-install the most recent version at <https://hua-zhou.github.io/TensorReg/>. If there're still errors, then you have to tell me the environment and a minimal example that reproduces the errors so that I can help.

**Comment by smszmr** [comment]
Hi Prof. Zhou,

I just uninstalled and reinstalled the toolbox. And it works well now. Thank you so much.

**Comment by lebornjj** [comment]
> Hi Prof. Zhou,
> 
> I have a question on the function tucker_reg. This function returns the parameters \beta in "glmstat2", which has a 1 \times 5 cell. I think the last one should be the final estimation. But there are only 2 numbers in the last item, and I'm not sure how to use them for new prediction on y.
> 
> Another question comes when I try to use the Sparse Tucker regression. There are always error massages, which are showed in the attached picture. I think there may be some modifications in the toolbox which are not updated online, is that right? <img alt="sparse" width="699" src="https://user-images.githubusercontent.com/22016945/27806743-5ee57cdc-600a-11e7-87c4-25c4f1860004.png">
> 
> Many thanks!

Hi smszmr
  I have a similiar question 

> Hi Prof. Zhou,
> 
> I have a question on the function tucker_reg. This function returns the parameters \beta in "glmstat2", which has a 1 \times 5 cell. I think the last one should be the final estimation. But there are only 2 numbers in the last item, and I'm not sure how to use them for new prediction on y.
> 
> Another question comes when I try to use the Sparse Tucker regression. There are always error massages, which are showed in the attached picture. I think there may be some modifications in the toolbox which are not updated online, is that right? <img alt="sparse" width="699" src="https://user-images.githubusercontent.com/22016945/27806743-5ee57cdc-600a-11e7-87c4-25c4f1860004.png">
> 
> Many thanks!

Hi smszmr

I have a smiliar question on the function kruskal_sparsereg. I have only used the demo_kruskal.m.And the issue is emerging when i ran the demo_kruskal.m to row 323-330,.
/% Estimate using Kruskal sparse logistic regression - lambda 1
% Warm start from rank 3 estimate/
And the issue showed that
'lsq_sparsereg' is not defined function or variable
error kruskal_sparsereg (line 282)
betatmp = lsq_sparsereg([Xj,eta0],y,lambda,'weights',wts,...
My pc is win and i use matlab2016a,and i use the lastest [TensorReg]1.0.3 . I hope you can help me.

Many thanks!
