### ISSUE TITLE
Error using horzcat

### ISSUE THREAD

**Issue by Haobo1108** [Hua-Zhou/TensorReg#3]
Dear Prof. Zhou,

I find a similar error concatenation error when I use kruskal_reg function.
[Code.zip](https://github.com/Hua-Zhou/TensorReg/files/4274982/Code.zip)

Error using horzcat
Dimensions of arrays being concatenated are not consistent.

Error in kruskal_reg (line 207)
                    Xj = reshape(Md{j}*khatrirao([beta.U(d:-1:j+1),cumkr]),...

I found that the error is generated at this step: [beta.U(d:-1:j+1),cumkr]. 

I have uploaded the script and the data. FYI, system: windows 10; matlab: R2019b. Thanks for your time!

Sincerely,
Haobo

**Comment by ibrahimcansu** [comment]
Hello @Haobo1108 

Did you solve the problem? Currently, I encounter same problem. 

Thanks,
Ibrahim.

**Comment by Haobo1108** [comment]
No. I didn't.

Best,
Haobo

**Comment by deeplearner0731** [comment]
use tensor toolbox 2.6 instead of 3.2

**Comment by lebornjj** [comment]
> use tensor toolbox 2.6 instead of 3.2

nb

**Comment by Hua-Zhou** [comment]
Update webpage (<https://hua-zhou.github.io/TensorReg/>) to point to Tensor Toolbox v2.6
