### ISSUE TITLE
error when using kruskal sparsereg.m

### ISSUE THREAD

**Issue by lebornjj** [Hua-Zhou/TensorReg#4]
Hi Prof. Zhou,

I have a question on the function kruskal_sparsereg. I have only used the demo_kruskal.m you gave. And the issue is emerging when i ran the demo_kruskal.m to row 323-330,.
                            /% Estimate using Kruskal sparse logistic regression - lambda 1
                            % Warm start from rank 3 estimate/
And the issue showed that    
                            'lsq_sparsereg' is not defined function or variable
                            error kruskal_sparsereg (line 282)
                                        betatmp = lsq_sparsereg([Xj,eta0],y,lambda,'weights',wts,...
My pc is win and i use matlab2016a,and i use the lastest [TensorReg]1.0.3 . I hope you can help me.

Many thanks!

**Comment by lebornjj** [comment]
> 

sorry  the error  take place in row 153-157 ,same error , not 323-330

**Comment by Hua-Zhou** [comment]
`lsq_sparsereg` is available from the SparseReg Toolbox: 
<http://hua-zhou.github.io/SparseReg/>

Please install the SparseReg Toolbox too.

**Comment by Hua-Zhou** [comment]
Update webpage (<https://hua-zhou.github.io/TensorReg/>) to add SparseReg Toolbox as dependency
